inherit_gem:
  relaxed-rubocop: .rubocop.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - db/schema.rb
    - bin/spring
    - config/deploy.rb
    - vendor/**/*
    - bin/*
    - node_modules/**/*

Metrics/BlockLength:
  Exclude:
    - "**/config/**/*.rb"
    - "**/spec/**/*.rb"
    - "**/app/views/**/*.json.jbuilder"

Style/CollectionMethods:
  PreferredMethods:
    find: detect
    reduce: inject
    collect: map
    find_all: select
    filter: reject

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Lint/EmptyBlock:
  Exclude:
    - "**/spec/factories/*.rb"

Bundler/OrderedGems:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes
  Enabled: true

Style/BlockDelimiters:
  EnforcedStyle: line_count_based

Layout/DotPosition:
  EnforcedStyle: leading

Rails/FilePath:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Lint/DuplicateBranch:
  Exclude:
    - "**/app/controllers/api/**/v1/*.rb"

RSpec/EmptyExampleGroup:
  Exclude:
    - "**/spec/requests/**/*.rb"

RSpec/VariableName:
  Exclude:
    - "**/spec/requests/**/*.rb"
    - "**/spec/support/shared/contexts/*.rb"

RSpec/ContextWording:
  Exclude:
    - "**/spec/requests/**/*.rb"
    - "**/spec/support/shared/contexts/**/*.rb"

RSpec/MultipleExpectations:
  Exclude:
    - "**/spec/channels/*.rb"

RSpec/LetSetup:
  Enabled: false

RSpec/ScatteredSetup:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false