version: "3.8"

services:
  postgres:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: twitter_backend
      POSTGRES_PASSWORD: twitter_backend

  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    tmpfs:
      - /app/tmp/pids
    env_file: .env
    stdin_open: true
    tty: true
    command: >
      bash -c "bundle install --jobs=$$(nproc) &&
               bundle exec rails db:create &&
               bundle exec rails db:migrate &&
               bundle exec rails s -b 0.0.0.0 -p 3000"

volumes:
  postgres_data:
