name: Rails CI/CD

on:
 push:
   branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      RAILS_MASTER_KEY: ${{ secrets.MASTER_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.0

      - name: Install dependencies
        run: bundle install

      - name: Run tests
        run: bundle exec rspec

      - name: Run rubocop 
        run: bundle exec rubocop
